# https://travis-ci.org/soimort/you-get
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  #- "nightly"  (flake8 not working in python 3.9 yet, module 'ast' has no attribute 'AugLoad')
  - "pypy3"
before_install:
  - pip install flake8
before_script:
  - flake8 . --count --select=E9,F63,F72,F82 --show-source --statistics
script: make test
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/43cd57826e88ed8f2152
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
